// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbCl5PX826Mptrj4uNWho4RLgotSIVg3E',
    appId: '1:677444936706:web:b38010ab3aa68b1372331b',
    messagingSenderId: '677444936706',
    projectId: 'eveningmovies-56845',
    authDomain: 'eveningmovies-56845.firebaseapp.com',
    storageBucket: 'eveningmovies-56845.appspot.com',
    measurementId: 'G-HD7HE6CVHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRivGpSBbtyOdX1KJIWzbnMFnXI9VnhA8',
    appId: '1:677444936706:android:0c4d181ab7d24d3d72331b',
    messagingSenderId: '677444936706',
    projectId: 'eveningmovies-56845',
    storageBucket: 'eveningmovies-56845.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOU-06oaY6qv-jsLfbEMIR32F5rh27tUo',
    appId: '1:677444936706:ios:c0c320aead0c5d9972331b',
    messagingSenderId: '677444936706',
    projectId: 'eveningmovies-56845',
    storageBucket: 'eveningmovies-56845.appspot.com',
    iosBundleId: 'com.example.moviesdb',
  );
}
